### ISSUE TITLE
Indexer: digitalcore.club error

### ISSUE THREAD

**Issue by sameep22** [autobrr/autobrr#1120]
**Version**
v1.29.0

**Describe the bug**
So I have been using autobrr to watch the releases on digitalcore.club IRC. However, I noticed that even though Digitalcore releases a movie/tv series I want, and that release is "approved", the torrent never gets added to my qbitorrent instance. I tried downloading the torrent file by clicking on the link, and I am getting an error which says "The user doesn't exist.".  On looking closely, it seems that the link used by autobrr has "/***my passkey***" appended to the torrent link. Removing the passkey manually from the URL seems to work.

**To Reproduce**
Download any torrent from digitalcore.club using the releases tab. 

**Expected behavior**
Download torrent file

System Info:
Ubuntu latest LTS server edition
Running as docker containers

Thanks,

**Comment by zze0s** [comment]
Hi! 

>  On looking closely, it seems that the link used by autobrr has "/my passkey" appended to the torrent link. Removing the passkey manually from the URL seems to work.

Do you mean copying the URL from autobrr and removing the passkey and paste it in your browser? That likely works because you are logged in on the site. Try the same in an incognito window or with `wget` or `curl` in a terminal and see what happens.

Are you sure you used the passkey and not some other key?

**Comment by zze0s** [comment]
@sameep22 Any updates? If not I'll close this.
