### ISSUE TITLE
Indexer Subsplease no longer functions

### ISSUE THREAD

**Issue by SnippetSpace** [autobrr/autobrr#1142]
Version v1.29.0

IRC for subsplease is connected, but releases are not parsed and do not show up on releases page.

1. add subsplease indexer
2. configure IRC on irc.rizon.net and connect to #subsplease channel
3. receive releases with this format: 
`[2023-09-21 19:12:17] CR-HOLLAND-IPv6|NEW: From #SubsPlease, come join the one stop shop for new anime * [1.4G] * [SubsPlease] Jujutsu Kaisen - 33 (1080p) [0FF2F2AC].mkv * /MSG CR-HOLLAND-IPv6|NEW XDCC SEND 14449`
4. check release page, nothing shows up.

**Expected behavior**
releases get parsed and displayed on the release feed

**Screenshots**
![sp2](https://github.com/autobrr/autobrr/assets/917744/ad368701-8462-4206-9130-d889741c8651)
![subsplease](https://github.com/autobrr/autobrr/assets/917744/56a3fb7f-986f-4d2f-9192-e65df8df5ec7)

**Additional context**
All other indexers work fine

**Comment by martylukyy** [comment]
Hi!

I just set this indexer up on my instance - along with a test filter - and couldn't reproduce this issue.
Please note that only releases matched by an enabled filter will show up on the releases page.
If there is no filter for that indexer that can match releases, the releases page will stay empty because of this.

Additionally, only releases announced by the `Katou` bot will be matched since other bots do not announce torrents.
