### ISSUE TITLE
Voyager for Alpharatio should be renamed to Theora 

### ISSUE THREAD

**Issue by bbtufty** [autobrr/autobrr#1297]
**Version**
Latest

**Describe the bug**
The IRC bot name has changed for Alpharatio (per https://alpharatio.cc/forums.php?action=viewthread&threadid=3689). Should now be Theora instead of Voyager. For now the IRC doesn't work, but changing this manually has fixed it

**Expected behavior**
IRC should connect

**Desktop (please complete the following information):**
 - OS: Synology
 - Browser Chrome
 - Version Latest

**Additional context**
N/A

**Comment by jimmyjones865** [comment]
note that 
- changing the invite command from "Voyager autobot..." to "Theora autobot..." works to get Autobrr connected to the announce channel (--> Autobrr documentation needs update)
- However, since the announce are now done by "Theora", Autobrr doesn't recognize and process the announces (--> Autobrr functionality needs update)
