### ISSUE TITLE
[FEATURE REQ] Override Indexer ID For Arr

### ISSUE THREAD

**Issue by kevinpastor** [autobrr/autobrr#1344]
**Is your feature request related to a problem? Please describe.**
I have an indexer configuration in Sonarr for a private tracker (TorrentLeech). This configuration named "TorrentLeech" lets me override the _Seed Ratio_ and _Seed Time_; this is to have different values for this private tracker than the default options I use for public trackers. When autobrr sends a release to Sonarr, the release is sent with the ID autobrr has for the indexer (`torrentleech`). This ID does not always match the name of the indexer in Sonarr (i.e. `"torrentleech" !== "TorrentLeech"`), causing it to fallback to the default indexer options.

**Describe the solution you'd like**
As it is possible to override the download client ID for a filter action, I would like to have the same feature applied to the indexer ID.

**Describe alternatives you've considered**
I thought about creating multiple download clients configurations in Sonarr, but "Seed Ratio" nor "Seed Time" cannot be set there; I would need to have multiple instances of my download client with for it to work.

I tried looking in the issues and discussions of this repository, but could not find anything regarding this problem.

**Additional context**
This problem also applies to Radarr.

I do think that setting the ID there (in the filter action) is the best place. In Radarr, I have two indexer configuration for TorrentLeech: one for Freeleeches named "TorrentLeech (Freeleech)", and one for the rest named "TorrentLeech". Having the indexer ID override in the filter action would allow each action to send the release as the right Arr indexer (e.g. freeleeches to "TorrentLeech (Freeleech)" and others to "TorrentLeech").

This feature could be problematic if a filter has multiple indexers selected. Instead of simply having an override for the ID, it could be some sort of table or selective override.

**Comment by appiekap653** [comment]
This is related to #961 and is something I have been waiting for.
The whole idea behind Prowlarr is to ease the setup of indexers from one central place and have them automatically updated into the *arr apps.
But when doing so it automatically adds the indexers with a sudden name: Tracker (Prowlarr)

In autobrr the indexers are automatically named: torznab-tracker

Because those two names are not equal issues #961 and #1344 are happening.

**Comment by zze0s** [comment]
Hey @bakerboy448 @thezak48 @mynameisbogdan your knowledge is needed here.

We have talked about this a couple of times on Discord but I can't find the previous discussions so lets go over it again here, if you don't mind. Add others with relevant knowledge if needed.

Do I remember correctly that the arrs (at least Radarr and Sonarr) had changes to the `release/push` endpoint and how it can handle indexer ID passed? Was it only numeric ID or does it take Indexer name as string as well?

We need to map autobrr and arr indexers together somehow.

1. We could add a new field to autobrr indexer settings like `Arr Indexer Name` where users can put in the name which if synced via Prowlarr will be like `Indexer (Prowlarr)`, and that works.
2. The other alternative is to add a numeric ID. That will however be an issue because when Prowlarr syncs to an arr it gets a separate numeric ID, which will be different per arr. Not great if you have 4 arrs (hd and uhd of sonarr and radarr).
3. We could pass the Prowlarr indexer ID or maybe even the full Prowlarr URL that is synced, like `http://prowlarr/3/`
4. Get the individual arr to store the "External Prowlarr Indexer ID" and then we can use that in autobrr to send to `release/push`
5. We add a new field to the autobrr indexer definitions that uses the same `indexer identifier` as the ones in prowlarr so it will be a string match instead of numeric int match? Most indexers in autobrr does follow the Prowlarr indexer identifiers but not all of them. Would this be easiest maybe? Will require changes on all ends but maybe it's viable
6. This was brought up before: a map of autobrr indexer name to specific arr indexer id. If you have 4x arrs in autobrr you'll need to do setup for each - not my first choice.

I think that's a start, happy to get the discussion going again so we can help our users.

**Comment by bakerboy448** [comment]
Yes looks like name can be detected to map to Starr indexer

https://github.com/Sonarr/Sonarr/blob/dac69445e4ab77fbce093b8dd859390e2e8fef2d/src/Sonarr.Api.V3/Indexers/ReleasePushController.cs#L87-L116

So autobrr just needs to support adding the Starr Indexer name on a per filter-action pairing I think

**Comment by Lokilicious** [comment]
Very much interested in this as this is currently the only reason i have autobrr disabled 👍

**Comment by kevinpastor** [comment]
Set it up last month and forgot about it. Just verified everything this morning and it works flawlessly. Thanks!
