### ISSUE TITLE
Not correctly monitoring IRC announcements for SpeedApp Tracker

### ISSUE THREAD

**Issue by EdTheLoon** [autobrr/autobrr#1392]
**Version**
1.36.0

**Describe the bug**
I have the indexer and IRC set up properly for SpeedApp. IRC is showing healthy and showing messages. However the 'last announce' always says N/A and none of the releases show up in the releases page. I also have a filter with this indexer enabled. In the logs, nothing shows up for this indexer except the IRC successful joining and monitoring messages.

**To Reproduce**
1. Add new indexer for SpeedApp.
2. Add relevant details such as passkey etc.
3. Login to IRC and register nick.
4. Add details to IRC section of autobrr.
5. Create new filter with test action.
7. Monitor releases and logs.

**Expected behavior**
Announcements from SpeedApp IRC show up in releases and get filtered.

**Screenshots**

![Screenshot 2024-02-04 175114](https://github.com/autobrr/autobrr/assets/911746/38d21497-306d-4654-9c93-53827e77801c)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 122

**Comment by EdTheLoon** [comment]
Forgot to attach logs screenshot.
![Screenshot 2024-02-04 180439](https://github.com/autobrr/autobrr/assets/911746/3e04b91a-60b3-4bbc-bd37-f37e1fa9b22f)

**Comment by s0up4200** [comment]
Hi there. This isn't technically a bug. If you look at the announcer name it has a 9 at the end. Autobrr looks for messages from `speedapp-announcer`, not `speedapp-announcer9`. This happens because they're failing to identify their bot with nickserv.

We're in the process of possibly making a solution for that on our end, but for now I'd tell their staff to fix it on their end.
