### ISSUE TITLE
"Years" field in one category inadvertently transfers to another category

### ISSUE THREAD

**Issue by luckylittle** [autobrr/autobrr#1496]
**Describe the bug**
_Years_ field in one category inadvertently transfers to another category (Movies and TV <=> Music)

**To Reproduce**
1. Start with a new filter, both **Movies and TV** as well as **Music** is empty:
![start1](https://github.com/autobrr/autobrr/assets/8032159/4a816ca5-108f-46c6-8eb3-1e08f12f3af5)
![start2](https://github.com/autobrr/autobrr/assets/8032159/78836b0b-6bda-4be4-9e53-cd0a8088aa95)
2. Add a new condition `Years = 2024` in the **Movies and TV** category:
![year1](https://github.com/autobrr/autobrr/assets/8032159/cbf9fa34-3692-44ce-b69a-88fb83ed6b1c)
3. Select the **Music** tab and suddenly it also contains the same condition `Years = 2024`:
![year2](https://github.com/autobrr/autobrr/assets/8032159/43688b54-1b78-44d2-8773-f56e63fc4693)

**Expected behavior**
I expect this field to be unique in it's own category and does not propagate to other category.

**Server:**
- OS: Raspbian `11.5` / `arm32v7`
- Version: `1.39.1`

**Desktop:**
 - OS: Red Hat Enterprise Linux release `9.2` (Plow)
 - Browser: Chromium `113.0.5750.0 custom build (64-bit)` & Firefox `102.13.0esr (64-bit)`

**Smartphone:**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Comment by zze0s** [comment]
Hi! Thanks for the report, however this is not a bug. 

It uses the same data field and it will only be checked once.

**Comment by luckylittle** [comment]
Hi @zze0s - it is not exactly logical though. It is confusing as it makes you think this will also download all music from 2024...

**Comment by zze0s** [comment]
It sort of will do that, unless you put in categories for movies/tv or resolutions, season/episode.

The field is parsed from the release name and if that is the only thing you filter for then everything matching the year will be downloaded. The different filter tabs are merely groupings of relevant filters, they do not have any logic for them to only work with one type of media.

I think you are the first one during these years and thousands of users to see this as an issue.

**Comment by luckylittle** [comment]
@zze0s If the year field is common for both types and is interchangeable, then perhaps it should be under the General tab instead

**Comment by zze0s** [comment]
I think most users are too familiar with how it is to change it and filtering by Year is mostly only used with Movies/TV and Music so it IMO makes sense for the field to be on both tabs.

The filters are pretty decent and does the job for most users, but they are not perfect for everyone and we have been discussing various improvements and total overhauls like a proper "rule based engine" where a user can select the field then operator (==,!=,<,>, contains etc) and have multiple of each and groups and sub rules and things like that, but that would cater more for advanced users and as with both open-source software and tools for companies we do have to think about who we are building things for and if it will benefit a lot of users or not. Some features we build just because it's fun tho :)
