### ISSUE TITLE
[FEATURE REQ] Detect language from the release name

### ISSUE THREAD

**Issue by luckylittle** [autobrr/autobrr#1498]
**Is your feature request related to a problem? Please describe.**
My understanding is, the language is being determined only if announced. So for example, this announce:
`[XXXX-XX-XX XX:XX:XX] <REDACTED>: -[new Musik]2[Artist-Album-CZ-EP-WEB-YEAR-GROUP]3[0000000]4[Size: XX.XX MB]5[FL: yes]6[Scene: yes]7[Pred XXs ago]` would not match the following filter:

```json
{
    "name": "<REDACTED>",
    "version": "1.0",
    "data": {
        "enabled": true,
        "freeleech": true,
        "formats": [
            "MP3"
        ],
        "match_categories": "Musik",
        "match_language": [
            "CZECH"
        ]
    }
}
```

**Describe the solution you'd like**
We should not rely on the announce, but instead determine the language (and other things) from it's name. This is already implemented in the `github.com/moistari/rls` that we use here:
* https://github.com/autobrr/autobrr/blob/b181231b12d0d7e2651cae1582f499238dcbc66b/internal/domain/release.go#L26
* https://github.com/autobrr/autobrr/blob/b181231b12d0d7e2651cae1582f499238dcbc66b/go.mod#L32

**Describe alternatives you've considered**
Alternative is to use regex e.g. for CZ & SK it would be something like `.*(-SK-|-CZ-|Czech|Slovak).*`

**Additional context**
N/A

**Comment by zze0s** [comment]
Hey! Some languages might be missing from the `rls` library.

> We should not rely on the announce, but instead determine the language (and other things) from it's name. 

Can you elaborate on this please? The announce usually contains the **release name** which we use for parsing with `rls`. There are usually other info in the announce that we map to various fields.
If there is a known language definition as part of it then it will be parsed as language.

**Comment by martylukyy** [comment]
I think the problem here is rather the fact that the posted filter, filters for MP3.
Seeing the announce neither we nor rls can know that this is a MP3.

I ran a test for this release name and it parses the following information from the name:
```
Artists:     "Artist"
Title:       "Album"
Language:    []string{"CZECH"}
Source:      "EP"
Group:       "GROUP"
[...]
```

So to clarify rls is able to parse CZECH with the following line:  

https://github.com/moistari/rls/blob/3cc39f680b5441111267f1fcb8067c1900a75bf4/taginfo/taginfo.csv#L339

This is not a language parsing issue imo but rather an issue about us not being able to know that it's MP3s.
To confirm this you can check the debug logs for rejection reasons.

**Comment by luckylittle** [comment]
@zze0s The misleading bit is the "if announced" here:
![Screenshot from 2024-04-11 12-44-06](https://github.com/autobrr/autobrr/assets/8032159/4e9283f5-7536-4f6f-91ba-e2f022bd3195)

Does that mean the language must be announced as a separate information, or is it determined from the name? From what you are saying, it sounds like it is determined from the name, which is the correct way IMHO.

@martylukyy Indeed i can confirm that the problem is with the format (language filter has not triggered yet, so can't confirm if that works yey). Debug log shows: `formats not matching. got: [] want: [MP3]`. In other words, this is working fine:

```json
{
    "name": "ALL_2024_Mp3",
    "version": "1.0",
    "data": {
        "enabled": true,
        "freeleech": true,
        "years": "2024",
        "match_categories": "new Musik"
    }
}
```

But this is not working:

```json
{
    "name": "ALL_2024_Mp3",
    "version": "1.0",
    "data": {
        "enabled": true,
        "freeleech": true,
        "years": "2024",
        "formats": [
            "MP3"
        ],
        "match_categories": "new Musik"
    }
}
```

Is the format determined from the name as well?

**Comment by zze0s** [comment]
> Does that mean the language must be announced as a separate information, or is it determined from the name? From what you are saying, it sounds like it is determined from the name, which is the correct way IMHO.

Both, some indexers have it as a separate tag and then we take that into consideration but usually it's part of the release name like your example above `Artist-Album-CZ-EP-WEB-YEAR-GROUP` and we always try to parse that.

> Is the format determined from the name as well?

Same thing there, some announce it separate from the name and others have it in the release name. With your example there's no format in there.

If it was like `Artist-Album-CZ-EP-WEB-MP3-YEAR-GROUP` it would indeed match your filter.

**Comment by martylukyy** [comment]
Allow me to elaborate further on both questions...

To add to your first question:
The description of that section might be a bit misleading thinking about it that way...
Maybe i will change the description to say `(if announced or in release name)` to be more precise... 🤔 

To add to your second question:
So this is where it gets a bit tricky unfortunately so let me present an example...
- `VA-Albumname-CD-1999-GROUP`
This is a MP3 release with scene conform naming.
As you can see you have no way of explicitly knowing that it is a MP3 since it is not in the name so we cannot parse it,  
if there is no other information provided by the announce line.

Assuming that it is a MP3 release if there is no format given is something i, personally am not very fond of,
since it might lead to misparsed releases.
That being said i don't remember if that has ever been considered/discussed  
and neither do i know if it's (easily) doable at the top of my head.

- `VA-Albumname-WEB-FLAC-2024-GROUP`
This is a FLAC release with scene conform naming.
As you can already see it has FLAC in the name so to answer your question:
Yes, autobrr is able to parse the format here.

With releases that do not have scene conform naming:
You are pretty much in the wild west in regards to what will be getting parsed or what won't be getting parsed 😅 
But if it's possible for us we do our best to parse information from release names that do not have scene conform naming.

**Comment by luckylittle** [comment]
First off, a huge thank you for creating such a fantastic tool! It has truly transformed the automatic downloading experience, making it simpler and more efficient for me. Your dedication to innovation (love the single Go binary) and user-friendly design together with simplicity shines through. Keep up the amazing work!

As for the matching - I would probably only stick to [scene rules](https://scenerules.org/) if i was you. They are well-defined and predictable and you would be easily able to match category there (e.g. separator for MP3 is `-`, whereas for Movies/TV it's `.` and there are certain keywords that also indicate what format is it).

**Comment by martylukyy** [comment]
You can already expect FLAC releases - under Advanced in the `Except releases` field just glob out or regex out FLAC.
That way you should only get MP3 releases according to the scene rules,
since no other audio formats for music are a thing in the rules anyway.

We discussed hardcoding this behaviour internally and are not really fond of it to be perfectly honest.

**Comment by zze0s** [comment]
Hey @luckylittle, did you get your questions answered? Can we close this or rename it to better reflect the discussion?

**Comment by luckylittle** [comment]
Yes, closing. I confirmed it can parse language.
