### ISSUE TITLE
Does the "DV HDR" matching catch something labeled as "DoVi HDR"?

### ISSUE THREAD

**Issue by flavorgold1** [autobrr/autobrr#1516]
There are many videos being released that are labeled as "DoVi HDR" or "HDR DoVi" (Profile 8).

Do you think we need to add these new labels?: "DoVi HDR" or "HDR DoVi"?

**Comment by s0up4200** [comment]
Hi!

The `DV HDR` option will match these releases.

Example release: `Movie 1998 2160p USA UHD Blu-ray DoVi HDR HEVC TrueHD 7.1 Atmos-GRP`

This will work, since it looks for releases that says DoVi/DV and HDR:
```JSON
{
    "name": "DoVi/DV+HDR test",
    "version": "1.0",
    "data": {
        "resolutions": [
            "2160p"
        ],
        "match_hdr": [
            "DV HDR"
        ]
    }
}
```

This will also work, since it will match on any of them:
```JSON
{
    "name": "DoVi and/or HDR test",
    "version": "1.0",
    "data": {
        "resolutions": [
            "2160p"
        ],
        "match_hdr": [
            "HDR",
            "DV"
        ]
    }
}
```

Now if the release was `Movie 1998 2160p USA UHD Blu-ray DoVi HEVC TrueHD 7.1 Atmos-GRP`, then only the last of the filters above would match, since it will match on either DV/DoVi or HDR, while the first filter would require both DV/DoVi and HDR to be present.

Hope that makes sense.
