### ISSUE TITLE
BLU RSS items have "0 bytes" size

### ISSUE THREAD

**Issue by anhtule88** [autobrr/autobrr#1603]
**Version**
1.44.0

**Describe the bug**
RSS has `<contentlength>` tags (and `Size` in `description` as well) but the releases show "0 bytes"

**To Reproduce**
1. Add any BLU RSS
2. Click on Releases to check the items.
3. All items from BLU RSS show "0 bytes"

**Expected behavior**
The sizes should be correctly parsed.

**Comment by Minituff** [comment]
I'm having this issue with TorrentLeech as well

**Comment by zze0s** [comment]
> I'm having this issue with TorrentLeech as well

In the case of TL using IRC they do not announce torrent size, so you need a min or max size in the filter for it to populate for filtering. There might however be a bug where it doesn't save the size after it has been processed. 

Might be the same for releases coming via RSS but need to debug that.

**Comment by Minituff** [comment]
Thanks @zze0s for the response.

Sorry if this is unrelated, but I just want to make sure I understand.

I expanded the example script you posted [here](https://autobrr.com/usage/tips#stop-if-disk-is-full) about stopping autobrr once the disk is full. I want it to also take into account the size of the torrent it is about to download.

But since TL doesn't announce torrent size...something like this won't work?
The `"{{.Size}}" "{{.SizeString}}"` params will always be 0?
![image](https://github.com/user-attachments/assets/dc2b2d0f-00f9-4406-9076-c0c0443a2566)

**Comment by zze0s** [comment]
That above should work because the extra size check (download .torrent file and parse size) happens before the External Filters run. That is unless there's a bug with this, but your logs should tell you if it has 0 or correct size in the exec args.
