### ISSUE TITLE
consolidate download before running actions

### ISSUE THREAD

**Issue by KyleSanderson** [autobrr/autobrr#179]
each action (on the same filter) results in a torrent download. That means with 4 actions that are applicable to the match, it will download the file 4 times as opposed to a single transfer. This end result of this is that sites with rate limiting fail some actions, and others pass. This is failing with 5xx errors usually.

![image](https://user-images.githubusercontent.com/1184902/158710430-756a811b-39c2-4b7e-8f3d-835b746a7089.png)

**Comment by ludviglundgren** [comment]
That's not how it works. If you check [here](https://github.com/autobrr/autobrr/blob/develop/internal/action/run.go) and see this on each action:
```golang
if release.TorrentTmpFile == "" {
	if err := release.DownloadTorrentFile(nil); err != nil {
		log.Error().Stack().Err(err)
		return err
	}
}
```

That explicitly check to see if the file already has been downloading it or not. So if there's multiple actions it will only download it once.

But knowing you have some special actions, maybe you're using the macro for `TorrentUrl` and downloading them in your scripts, rather than using the `TorrentPathName` which is to the file in `/tmp` on disk already downloaded?

**Comment by KyleSanderson** [comment]
Just the name, mousing over the fail reason shows it as failing with error 500 for the same push. 

`That explicitly check to see if the file already has been downloading it or not. So if there's multiple actions it will only download it once.`

I'm seeing it racing based on the async calling function, which would support the multiple download theory.
