### ISSUE TITLE
Error HTTP request to 'api/auth/login' failed with code 500 (could not create cookies)

### ISSUE THREAD

**Issue by Tontze** [autobrr/autobrr#1869]
App Version:
v1.52.0 

![Image](https://github.com/user-attachments/assets/09fa57c5-6a06-480c-863b-274fdb0bf2fa)

Install container in truenas electric eel

After setting username and password in initial screen, i suppose you should get to log in :) Instead it gives error in the picture above.

**Desktop (please complete the following information):**
 - OS: TrueNAS Electric EEL
 - Browser Firefox latest

Its propably some permission problem on truenas, but have no idea where and what, could use a little help :)

**Comment by zze0s** [comment]
Hi! That is most likely a permissions issue. Check the logs if it has an issues related to creating the database. We don't do any S6 overlay docker magic so you need to create and own the config dir before you map it.

**Comment by Tontze** [comment]
I can see from logs that it fixes permissions, but then it says chmod is falsy ? 

`2024-12-08 21:34:11.248307+00:00=== Applying configuration on volume with identifier [config] ===
2024-12-08 21:34:11.248338+00:00Current Ownership and Permissions on [/mnt/permission/config]:
2024-12-08 21:34:11.248345+00:00Ownership: wanted [568:568], got [0:0].
2024-12-08 21:34:11.248349+00:00Permissions: wanted [None], got [0755].
2024-12-08 21:34:11.248354+00:00---
2024-12-08 21:34:11.248362+00:00Ownership is incorrect. Fixing...
2024-12-08 21:34:11.248367+00:00Changing ownership to 568:568 on: [/mnt/permission/config]
2024-12-08 21:34:11.248371+00:00Ownership after changes:
2024-12-08 21:34:11.248376+00:00Ownership: [568:568]
2024-12-08 21:34:11.248380+00:00Skipping permissions check, chmod is falsy
2024-12-08 21:34:11.248388+00:00Time taken: 0.22ms
2024-12-08 21:34:11.248393+00:00=== Finished applying configuration on volume with identifier [config] ==
2024-12-08 21:34:11.248398+00:002024-12-08T21:34:11.248398099Z
2024-12-08 21:34:11.248402+00:00Total time taken: 0.27ms
`

Propably need to try without truenas's ix-volumes autocreated dirs, easier to follow..

**Comment by Tontze** [comment]
Also: 

``` 2024-12-09 06:22:40.043168+00:00{"level":"error","module":"http","error":"securecookie: the value is not valid","time":"2024-12-09T08:22:40+02:00","message":"Auth: Failed to create cookies with attempt username: ```

**Comment by Tontze** [comment]
Ok, managed to get it working, first installed it with root user, then changed it to normal user and chowned all the dirs.

**Comment by bobobo1618** [comment]
I hadn't touched my container in quite a long time but tried to log in and ran into this same message. I'm getting messages like these:

`{"level":"error","module":"http","error":"securecookie: base64 decode failed - caused by: illegal base64 data at input byte 127","time":"2025-01-24T16:59:02Z","message":"Auth: Failed to create cookies with attempt username: [<username>] ip: <ip>"}`

The only other interesting-looking message is this:

`{"level":"warn","module":"http","warning":"onboarding unavailable","status":503,"time":"2025-01-24T16:59:00Z","message":"server warning"}`

My log level is debug but I don't see any evidence of permissions issues.

I opened an incognito tab and tried to log in and it worked, so this points to issues with the browser's cookies.

The browser with bad cookies had a cookie containing URL-encoded colons (`%3A`) in the `user_session` cookie and doesn't parse as valid base64. If I remove the URL-encoded colons and base64 decode the first truncated section, I get JSON.

The browser with good cookies had a much longer cookie with no colons and base64 decoding it results in a string with what looks like pipe-separated values, the first of which is a UNIX timestamp.

I think this is a real bug: the format of the `user_session` cookie changed at some point and attempting to log in with an old cookie causes 500 errors.
