### ISSUE TITLE
excessive metadata collection

### ISSUE THREAD

**Issue by KyleSanderson** [autobrr/autobrr#194]
This is going to be an annoying one because it's going to require the data collection to happen upon actual request. However, now that this is serialized it's going to be easier to implement as-is.

Presently whenever (specific) actions are run a torrent is queried/downloaded even though the information needed is not requested.

This is the case for ActionTypeExec and ActionTypeWebhook. (I'm leaving out obvious others, like client pushes + watchdir.)

With BTN, RED, GGN, and PTP the situation becomes a bit more serious as they have rate limiting per hour. Now, the situation becomes an ordering condition. If the information is fed into *arr, the API is called. If this action is rejected, and hits any other type the torrent will then be downloaded. Worse, mixed with a Webhook or Exec as well in the action, there's the API call + 2 downloads now (one from Sonarr, and another from autobrr).

**Comment by KyleSanderson** [comment]
https://github.com/autobrr/autobrr/blob/cb6cbb83d5424a6061aa4536fa24a6742c5b5ac1/internal/filter/service.go#L260

**Comment by ludviglundgren** [comment]
What about a toggle like say `skip tmp download` in the action where it's up to the user to decide if that's what they want.

It could default to false for arr and webhook actions and probably the webhook as well. That way you can control what it does. Say you only have a webhook action that does something, and that may or may not need the data.

This doesn't take the `AdditionalSizeCheckRequired` into consideration tho, since that is a filter thing, and avoidable.

**Comment by KyleSanderson** [comment]
I think it's fine to add that, but it feels like it's moving the technical issue to an end-user configuration as opposed to doing the right thing.

**Comment by ludviglundgren** [comment]
But what would the right thing actually be?

Exec is meant to run scripts, and those script might or might not need the file downloaded so making it optional would be the right thing IMO. 
Same thing with the webhook.

The arr shouldn't grab the file, unless the filter size check requires it. 

Today thats only done if:
1. The filter has a min or max size
2. The announce doesn't have size
3. The indexer doesn't use api

I'm not 100% sure that size is actually needed for the arr, so will double check that. But doing a mix of action might still require a download.

With the recent introduction of notifications that removes some need for excess downloads. And will soon add the cross-seed integration which will happen before the filters even run and will only download the file if it's a match, otherwise continue to filter checks.

**Comment by KyleSanderson** [comment]
> Exec is meant to run scripts, and those script might or might not need the file downloaded so making it optional would be the right thing IMO.

The right thing in this scenario is where would you be able to use the file. You'd need to use the torrentfilename macro.

So I think the "right" thing here, is outside of the predetermined fields, is if the macro is requested and the data isn't there - take the action to collect the required data to proceed.

**Comment by ludviglundgren** [comment]
That should be manageable to do! Will look at it coming days :+1:
