### ISSUE TITLE
Add stack trace logging on crash/fault signal (Linux/macOS)

### ISSUE THREAD

**Issue by stacksmash76** [autobrr/autobrr#231]
Windows will need a custom EH, which is maybe a nice TODO for some future times.

E: Should cover at least 5 frames up with demangled symbol names, if possible. Otherwise, at least log caller RVA's.

**Comment by zze0s** [comment]
Currently it writes to stderr on panic with a stacktrace but it does not write the stacktrace to log file if it's enabled. On linux it can be checked with `journalctl` if running with systemd, and with containers the logs for docker and k8s shows it since it was captured from stderr.

This is imo good enough to debug issues and it's already proven helpful.
