### ISSUE TITLE
Notify on updates

### ISSUE THREAD

**Issue by ludviglundgren** [autobrr/autobrr#319]
Notify of available updates, with banner and in settings. Fetch on schedule, or manually.

## Future goals

- Auto update
- Update "in place" for non docker env.

**Comment by stacksmash76** [comment]
Issue #267 is related to this one. It should probably get closed, since this one is more general.

**Comment by KyleSanderson** [comment]
> Issue #267 is related to this one. It should probably get closed, since this one is more general.

I'd actually say that the aforementioned request is more specific to "this version upgrade has no downgrade path" as opposed to "stable version 9 is out, review the changelog and update 😸". We never want to strive for downgrades (because that means something has gone wrong), but letting users know when the database schema changes should be part of the changelog explicitly. We're still in Alpha or Beta right now, so drastic changes are OK. However, once Stable ships, DB schema changes should be treated much more seriously and only on a "major" version change.

A thought - anyways.
