### ISSUE TITLE
Base url doesn't work in docker

### ISSUE THREAD

**Issue by tom0010** [autobrr/autobrr#322]
When using traefik with no base url, I can successfully connect to autobrr. 

When I edit the config.toml to `baseUrl = "/autobrr/"` along with traefik ``PathPrefix(`/autobrr/`)`` I get a white screen on the browser. When I do a curl I get back:
```html
<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="./static/favicon.ico"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="autobrr"/><link rel="apple-touch-icon" href="./static/logo192.png"/><link crossorigin="use-credentials" rel="manifest" href="./static/manifest.json"/><title>autobrr</title><base href="/autobrr/"><script>window.APP={},window.APP.baseUrl="\/autobrr\/"</script><script defer="defer" src="./static/js/main.9642c6cf.js"></script><link href="./static/css/main.a1f27050.css" rel="stylesheet"></head><body class="bg-color"><noscript>You need to enable JavaScript to run this app.</noscript><div id="root" class="pattern"></div></body></html>
```
When I inspect the the webpage using dev tools, I don't see any problems, actually all I see is 200s, so that looks good to me. 

But it does turn out that it is returning the same info as the snippet above.

Going back to removing `baseUrl` along with the `PathPrefix` in traefik, it works all over again using `https://mydomain`

I've tried on the latest version and also on v0.25.0.

**Comment by stacksmash76** [comment]
Hi there!

There's one key component you're missing: rewriting the URL after traefik matched it for the base path to work correctly. See https://github.com/swizzin/swizzin/blob/df9e299290fd20f5e88de819ddab61c77d8569c5/scripts/nginx/autobrr.sh#L18
In traefik, from what I can tell, you can do this with `PathPrefixStrip`.

This feature might need some additional attention in the future in order to change this behavior (and also get documented properly). As of right now, it'll suffice.

**Comment by tom0010** [comment]
That worked - thanks for the quick response. 

Would be good to add to the documentation along with having to change the host from `127.0.0.1` to `0.0.0.0`, I only found that out by looking in discord.
