### ISSUE TITLE
Default username and password?

### ISSUE THREAD

**Issue by wazar** [autobrr/autobrr#37]
I get the binary to run but the web-gui is behind an auth page, and I can't seem to find any references to default creds.

**Comment by brettpetch** [comment]
you need to set the password in the config.

```
autobrrctl --config /path/to/your/config/file create-user username
```

**Comment by wazar** [comment]
Tested on two machines, Debian 11

`mikew@lt4-3-10sentnel:~/autobrr$ ./autobrrctl --config config.toml create-user mikewazar
2021/11/24 05:07:25 could not migrate db: failed to query schema version: unable to open database file: out of memory (14)`

**Comment by ludviglundgren** [comment]
It does indeed not have any default credentials.

To create a user with `autobrrctl` you pass the location/directory of the config file, instead of directly the config file. Maybe a bit confusing. It's still early in development and lacking documentation.

`./autobrrctl --config . create-user USER`

Where . (dot) being the current dir if the config is there. Otherwise point it to the full path.

Hope that helps!
