### ISSUE TITLE
`PUID`/`PGID` config is not functional

### ISSUE THREAD

**Issue by agneevX** [autobrr/autobrr#415]
Hello!

I deployed an initial container with a correct PUID/PGID. However, it created the initial files as root.

The container also runs as root instead of running as the PUID/PGID user.

The fix is deploying the container as `user: "1000:1000"`.

**Comment by zze0s** [comment]
HI! Thanks for reporting this.

Do you know what would happen with existing installs when this is fixed? The files will be owned by root then, so do we need some extra init script to take ownership?

**Comment by agneevX** [comment]
These might help you :)

https://github.com/hotio/radarr/blob/nightly/root/etc/cont-init.d/00-start-container

https://github.com/hotio/radarr/blob/nightly/root/etc/services.d/radarr/run

**Comment by onedr0p** [comment]
IMO this app should not use s6-overlay because it has no purpose to use it.

Ideally the app should run as `1000:1000` by default and people can change the user using docker/docker-compose. 

Take a look at Recylarr for example how they are doing permissions:

- https://github.com/recyclarr/recyclarr/wiki/Docker#docker-compose-example
- https://github.com/recyclarr/recyclarr/wiki/Docker#permission-issues

**Comment by fabricionaweb** [comment]
Just passing the user and group to Docker seems to worked to me.

https://docs.docker.com/engine/reference/run/#user
