### ISSUE TITLE
[Bug] metainfo syntax error - unknown value type '<'

### ISSUE THREAD

**Issue by 6ftClaud** [autobrr/autobrr#520]
**Describe the bug**
Autobrr cannot read torrent info
```
Filter: error downloading torrent file for release: <release name>: All attempts fail:
#1: metainfo could not load file contents: /tmp/autobrr-1557958633: bencode: syntax error (offset: 0): unknown value type '<'
#2: metainfo could not load file contents: /tmp/autobrr-1557958633: bencode: syntax error (offset: 0): unknown value type '<'
#3: metainfo could not load file contents: /tmp/autobrr-1557958633: bencode: syntax error (offset: 0): unknown value type '<'
```

**To Reproduce**
1. Add torznab feed
2. Setup filter
3. Wait

**Expected behavior**
Autobrr should inject the torrent into the qBittorrent client.

**Screenshots**
![image](https://user-images.githubusercontent.com/54559822/199979118-068ea158-8385-4896-bbed-66c9bdd0f832.png)

**Docker (please complete the following information):**
 - Docker version: `20.10.21`
 - Autobrr image version: `v1.9.0`

**Comment by zze0s** [comment]
Hi!

This error means that autobrr didn't get a proper or full `.torrent` file, and the `<` would indicate it's a html file instead since they start with `<html>`.

Did the feed test **OK**? Is the feed coming via Prowlarr or Jackett? Those are the ones we've tested for Torznab feeds.

Side note: RSS feeds can be used directly from the sites.

**Comment by 6ftClaud** [comment]
Hi :) 
I just tested the feed in autobrr and it returned OK. I'm using it with Jackett.
Did a manual search with Jackett and that specific tracker returns results just fine as well.

**Comment by zze0s** [comment]
If you visit the feed url with your browser, can you copy any of the download links then and try that in a private browser window and see if it works? The feed works since it goes to filters etc, but then fails in the action where it downloads the torrent.

If you can try some other indexer with torznab that would also be good to see if it's indexer specific or not.

**Comment by 6ftClaud** [comment]
Sorry, I can't find any Jackett documentation on how to pass an API key to the request. How's the header token named?

**Comment by zze0s** [comment]
They apikey for Jackett can be sent as a query param like `http://DOMAIN/jackett/api/v2.0/indexers/INDEXER_HERE/results/torznab/api?apikey=XXX`.

**Comment by 6ftClaud** [comment]
Alright, seems like I found where the issue is. I'm using Authelia and I whitelisted `/api` URLs, but Jackett uses `/dl` URLs to actually download the torrents. Since it wasn't whitelisted, it was asking for authentication and it couldn't download the torrent. Thanks for the help :) A bit of a non standard configuration here kinda.

**Comment by zze0s** [comment]
Great! Always happy to debug stuff to know it's not an autobrr issue ;)

Closing this then. Enjoy your friday!
