### ISSUE TITLE
[FEATURE REQ] Assign ruTorrent ratio group and/or channel per filter

### ISSUE THREAD

**Issue by ben-burns** [autobrr/autobrr#788]
**Is your feature request related to a problem? Please describe.**
With torrents that are snatched from autobrr, I have to manually assign a ratio group and/or channel to the torrent in ruTorrent.  This is a functionality that exists with autodl-irssi + ruTorrent.

**Describe the solution you'd like**
If the client is rTorrent, allow the ability to populate ratio group and/or channel in the Actions section for each filter.  Both ratio group and channel should be optional as not everyone may utilize the fields, or may prefer one over the other.

**Describe alternatives you've considered**
Current alternatives is just to manually assign a ratio group or channel in ruTorrent for each torrent added by autobrr.  While this method works, it would provide a velocity increase to not have to manually assign a ratio group every day to each torrent.

**Additional context**
An example of the additional fields in the actions section could look something like this:
![Ratio group and channel filter mockup](https://i.imgur.com/kkVt4Z4.png)

**Comment by metonyms** [comment]
i'll leave my notes here since i've been chugging along on various r(u)torrent action options. i don't use either of these options so my knowledge may be limited

both are pretty straightforward to implement as a freeform text box since all you need to set is [`d.throttle_name.set`](https://github.com/autodl-community/autodl-irssi/blob/b534cbecd6f85a534034a002438ed12a0432028f/AutodlIrssi/MatchedRelease.pm#L674) (channels) or [`d.views.push_back_unique` and `view.set_visible`](https://github.com/autodl-community/autodl-irssi/blob/b534cbecd6f85a534034a002438ed12a0432028f/AutodlIrssi/MatchedRelease.pm#L673) (groups). the reason for a text box is that i don't see an easy way to pull the ratio group/channel names from ruTorrent since the "api" is basically just a global object. i'd appreciate if someone has an example of an external program that can grab those

however there is a simpler way that is built into ruTorrent, the [ExtRatio plugin](https://github.com/Novik/ruTorrent/wiki/PluginExtRatio) lets you setup assignment rules for either channels or ratio groups (thanks to bobert for bringing this up in discord)

if there is still a good reason to implement this in autobrr i'm all ears but for now i don't think it is necessary

**Comment by ben-burns** [comment]
Thanks for reply, @metonyms.  I forgot about ExtRatio as I had been using autodl-irssi to add a ratio group for me, instead. 

It does make sense to use the ExtRatio plugin that is built into ruTorrent versus duplicating this functionality in autobrr. I'll close this for now since you are right, it's likely not necessary.
