### ISSUE TITLE
Dev Environment?

### ISSUE THREAD

**Issue by KaiserBh** [autobrr/autobrr#84]
Hi there,

Quick question how would one run this in development environment?
I managed to build the dockerfile and run it using docker-compose but then I couldn't login since I need to create a user I believe.
So how does one manage to get the dev environment running? 

Regards,
kb

**Comment by ludviglundgren** [comment]
Hi!

Depends on if you are developing/adding indexer support or doing general dev.

For development I personally run it with the debugger in Goland. VS Code has one as well. You can run it with just `go run cmd/autobrr/main.go` as well. You also need Node + NPM/Yarn to be able to build the frontend. 

It will not run unless the files are compiled, so workflow would be:

* Checkout repo
* `cd web && npm run build`
* Then back to the root, and either use `go build` or `go run`

There's also a Makefile with some commands to build. As well as `goreleaser` to build multi Arch binaries for linux and windows.

The Dockerfile is more meant as a build env and final run container, since it uses multi-stage builds.

In `test/integration` there's a docker-compose with a irc server you can run locally do try things out. I have 2 Mock Indexers I use locally with that irc server. They were in the repo breifly but have since removed them because it needs a better solution for dev mode etc. They can however be found here https://github.com/autobrr/autobrr/commit/ebed38a16c637c123205eee8462007638c380e7a

We have a Discord server as well if you want to discuss things in more real time. :slightly_smiling_face:  https://discord.gg/YKnfTRdw

**Comment by KaiserBh** [comment]
Thank you @ludviglundgren, I was looking more into both actually developing/adding indexer support and general dev. 
I will try to get it running locally and be sure to join the discord server.
