### ISSUE TITLE
[FEATURE REQ] Secure storage of authentication for rTorrent

### ISSUE THREAD

**Issue by A69Tor** [autobrr/autobrr#858]
**Is your feature request related to a problem? Please describe.**
Currently the username and password for ruTorrent URLs are stored in plain text.

**Describe the solution you'd like**
Separate input fields for username and password with proper secure storage of password and obfuscation of password in GU

**Comment by zze0s** [comment]
Hi,

Storing _secrets_ in an app like this can be troublesome. Currently everything except the actual user login for autobrr itself is stored in plaintext.

Why? Because simplicity and because there would have to be a way to decrypt all info on startup otherwise. That's not convenient for servers which can crash, or restart, or autobrr crash and restart etc.

The user login is easy since then you actually do supply your key and it does the comparing etc. I suppose we could add a new config key that is a salt/secret etc and use that, but that would still be on disk and if someone gets access to disk they have access to the SQLite db as well, and Postgres via the `config.toml`.

We're open for feedback to improve this :)

With that said, the current implementation for rTorrent is indeed bad. It's a 3rd party library and it does not have methods to store/use Basic Auth info separately. It does however have the ability to set our own `http.Client` I found out after the initial implementation, so we should be able to use that. Otherwise we might have to fork it.
