### ISSUE TITLE
Enabled state does not get refreshed when opening a filter.

### ISSUE THREAD

**Issue by martylukyy** [autobrr/autobrr#864]
**Version**
v1.24.1

**Describe the bug**
Enabled state does not get refreshed when opening a filter or when changing the enabled status in the filter list.
This causes a wrong status shown in the filter itself when enabled/disabled it before on the filter list.

**Video to Reproduce**

https://user-images.githubusercontent.com/35452459/233610836-7776c95f-8d42-4c2f-b161-124d8727a4e0.mp4

**Expected behavior**
When enabling/disabling a filter on the filter list and opening it afterwards it should show the correct status.

**Additional context**
If I read the code correctly, it should already invalidateQueries, but it seems like it does not?
https://github.com/autobrr/autobrr/blob/286f2f53f74c465f7e3d37857665a359c96b0f85/web/src/screens/filters/list.tsx#L636-L658
https://github.com/autobrr/autobrr/blob/286f2f53f74c465f7e3d37857665a359c96b0f85/web/src/screens/filters/list.tsx#L673-L675

Adding a invalidation to the filter.name fixes it, but feels wrong because it takes pretty long to open the filter then 
and it looks like a hard refresh...

This should be a simple queryClient.invalidateQueries somewhere but i don't know where to put it
since where i would put it, it is either already there or it takes pretty long to open the filter then and it looks like a hard refresh...

**Comment by stacksmash76** [comment]
So many things wrong with filters. To name a few:
- don't fetch filter 0 when no filterId specified, rather 404 (I don't even think filterId can be empty on that route, one should consult react-router docs)
- don't navigate to `/filters/0` on error (hello, recursion?)
- use invalidateQueries instead of refetchQueries

Precisely, this issue is a type problem with query keys:
- list.tsx: `queryClient.invalidateQueries(["filters", filter?.id]); ` id is an integer here
- details.tsx `useQuery(["filters", filterId], ...)` filterId is a string here

What should've been done in the first place was to unify query keys with api calls in a single function and use the spread syntax to get rid of type-unsafe keys (recall that we once got bit in the ass since we missed an 's' in one of the keys).

Lot's more to be written, but good luck to feature maintainers. react-query v3 changed the query key syntax in some cases, and v4 also changed it! Great!
