### ISSUE TITLE
Fuzer IRC Indexer isn't parsing announcements properly

### ISSUE THREAD

**Issue by danshus** [autobrr/autobrr#949]
**Version**
1.26.2

**Describe the bug**
After configuring the Fuzer IRC Indexer, announcements are recognized properly. When you attempt to grab the torrent, you receive the following - 

'Rejected: All attempts fail:
#1: unexpected content type 'text/html; charset=UTF-8': check indexer keys for fuzer'

This issue, isn't observed on autodl-irssl with identical configurations, the RSS Key is configured properly (though I'm not sure if it's relevant).

**To Reproduce**
1. Configure Fuzer indexer
2. Configure a simple filter to grab FreeLeech announcements
3. Action -> rTorrent
4. Wait for a release
5. See the error

**Expected behavior**
The torrent should be grabbed and parsed successfully to rTorrent.

**Screenshots**

![image](https://github.com/autobrr/autobrr/assets/27550593/6d6368f1-984d-48c9-b20d-f2120e2508ec)

**Desktop (please complete the following information):**
N/A

**Additional context**

This was troubleshooted with the support staff of Fuzer, the claim of 'Autobrr isn't parsing the IRC announcments properly' comes from them, as this issue appears to be known. If you require additional information, I can ask them to reply here

tracelog - 

16:29:59.000TRACE incoming_request
16:29:59.000TRACE incoming_request
16:30:00.000TRACE query: 'SELECT r.id, r.filter_status, r.rejections, r.indexer, r.filter, r.filter_id, r.protocol, r.info_url, r.download_url, r.title, r.torrent_name, r.size, r.timestamp FROM release r WHERE r.id = $1 ORDER BY r.id DESC', args: '[6]'
16:30:00.000TRACE release.store_release_action_status: &{ID:9 Status:Pending Action:Download ActionID:2 Type:RTORRENT Client:rTorrent Filter:Default1 FilterID:2 Rejections:[] ReleaseID:6 Timestamp:2023-05-21 15:30:00.53136583 +0200 CEST m=+78769.191586757}
16:30:00.000DEBUG action rTorrent: Download
16:30:00.000ERROR could not download torrent file for release: Greys.Anatomy.S19.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb
16:30:00.000ERROR process action failed: Download for 'Greys.Anatomy.S19.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb'
16:30:00.000TRACE events: 'PUSH_ERROR' '&{Subject: Message: Event:PUSH_ERROR ReleaseName:Greys.Anatomy.S19.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb Filter:Default1 Indexer:fuzer InfoHash: Size:27010000000 Status:Error Action:Download ActionType:RTORRENT ActionClient:rTorrent Rejections:[All attempts fail: #1: unexpected content type 'text/html; charset=UTF-8': check indexer keys for fuzer] Protocol:torrent Implementation:IRC Timestamp:2023-05-21 15:30:00.64627581 +0200 CEST m=+78769.306496767}'
16:30:00.000ERROR release.runAction: error running actions for filter: Default1
16:30:00.000ERROR release.retryAction: error running actions for filter: Default1
16:30:00.000TRACE release.store_release_action_status: &{ID:9 Status:Error Action:Download ActionID:2 Type:RTORRENT Client:rTorrent Filter:Default1 FilterID:2 Rejections:[All attempts fail: #1: unexpected content type 'text/html; charset=UTF-8': check indexer keys for fuzer] ReleaseID:6 Timestamp:2023-05-21 15:30:00.53136583 +0200 CEST m=+78769.191586757}

**Comment by zze0s** [comment]
Hi!

That issue comes from when it tires to download the .torrent file and pass onto the download client. It's usually because of wrong keys like RSS key used.

If you check the Releases page instead of the Dashboard, it will have this icon:
![image](https://github.com/autobrr/autobrr/assets/43699394/358bcb96-85c9-49f1-a5f0-6248ccc01384)
That is the link autobrr uses to download the .torrent file. Right click and copy link, then open a Incognito browser window and paste that in the url, and hit enter. If that does indeed work, then the issue is on our end and they have the wrong content-type which we interpret as an issue.

If it does give an error, read the full url and see if there's anything looking off.

In the definition and settings for Fuzer we have User ID and Passkey which it needs both values. The help text says to get them from the RSS link, and find them in the url. You must copy and paste the values manually and not the full link.

Let me know how it goes :) I know of other users using it without any issues, properly setup.

**Comment by danshus** [comment]
Thanks for the quick response!

I did your exact steps for repro and managed to DL the .torrent file in an incognito tab.

I can hop on discord real quick and share with you the full URL with the uid + passkey to show you it works properly...

**Comment by danshus** [comment]
As a follow up - the staff of Fuzer have acknowledged this issue and are going to fix it sooner or later, though they weren't keen on giving an ETA :)
