### ISSUE TITLE
Nickserv should not be mandatory

### ISSUE THREAD

**Issue by ThisIsTheOnlyUsernameAvailable** [autobrr/autobrr#96]
Amazing project!

I connect to IRC via ZNC so do my authentication and session management via it.  I therefore don't need autobrr to auth to a Nickserv and believe it should be an option rather than a mandatory field.  I'm sure there are other use cases that do not need NickServ integration.

Can this functionality be changed to optional?

**Comment by ludviglundgren** [comment]
Hey! Thanks!

The idea behind how it's setup is to make the user aware of if they need to have a registered/nickserv account or not to connect to X network and access Y channel. All to make it easier to onboard new users/indexers etc without having to look at all the details on the indexer/tracker.

And it's really only using NickServ if there's a password, otherwise it's just a regular nick. Might be slightly misleading.

Network is also used in the code for some checks etc. I get that it would be nice to connect with your already setup bouncer but it's not really possible the way things are built. There could also potentially be other issues running it through a bouncer.

I suggest you create additional nicks and group them with your main :slightly_smiling_face:

**Comment by ludviglundgren** [comment]
I'll close this for now since there hasn't been any answers. I think the reasoning behind it, and explanation is good enough considering the solution is simple.
