### ISSUE TITLE
Transmission re-announce

### ISSUE THREAD

**Issue by miczlo** [autobrr/autobrr#996]
**Version**
Latest version deployed with compose

**Describe the bug**
Might be Transmission and not autobrr
Torrents get added but stalled at idle and need stop start to download

**To Reproduce**
Wait for the torrent to be added to transmission -doesn't download
stop start - downloads

**Expected behavior**
Torrent downloads

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Synology
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 114.0.5735.134

**Additional context**
Autobrr logs look healthy
If I add torrent manually to transmission it works fine
Both are within same compose, connection direct using hostname

**Comment by zze0s** [comment]
Hi!

Is this with TL, IPT or some other indexer? With those they often need re-announce because there is a delay between the indexer and the actual torrent tracker. When adding manually it's way slower and they are in sync.

With qBittorrent we have built in re-announce, and with Deluge you have to use external scripts that run on Add in the client to trigger re-announce. 

We do not currently have this built in for Transmission but a PR was started to introduce it https://github.com/autobrr/autobrr/pull/708

**Comment by miczlo** [comment]
Yeah it's TL. Thanks for clarifying - it makes sense. I'll try qbit maybe
then.
